"""mHGS, reproduced per Hashim et al. (2023), "Dimensionality reduction
approach based on modified hunger games search: case study on Parkinson's
disease phonation".

Implements the five modifications over the base Hunger Games Search (Yang
et al., 2021): modified production operator (Eq. 19), modified local
escaping operator with a best-4-agents delta (Eq. 21-22), the Shrink-based
transition factor (Eq. 23), and the modified two-strategy cooperative
communication update that replaces HGS's original Eq. 1 (Eq. 24).

Positions live in [0,1]^D (Eq. 25) and are thresholded at 0.5 (Eq. 26); the
paper's own kNN-based fitness (Eq. 27) is replaced by this project's shared
FitnessEvaluator. Population size and max iterations are not stated
explicitly in the paper (only inferable as ~100 from a convergence-plot
axis) -- defaults below are this project's own choice, not from the paper.

mLEO gap: the paper's own modification to LEO is scoped to the delta term
only (Eq. 22, using the mean of the 4 best agents in place of 4 random
ones -- implemented exactly below). The rest of Eq. 15's bracketed
correction term is inherited unmodified from GBO's Local Escaping Operator
and involves S1/S2 candidates generated by GBO's Gradient Search Operator
plus two random population members (Sr1, Sr2). Unlike this file's other
gap-fills, the paper DOES give that machinery's formula in full (Algorithm
2's pseudocode and Eq. 11-14 for the Gradient Search Operator) -- it is not
a case of the paper omitting it. This implementation nonetheless drops that
S1/S2/Sr1/Sr2 correction term and applies k1*(v1*best-v2*Sk) + k2*k1*v3*delta
directly -- a deliberate simplification of Eq. 15 for implementation
complexity, not a paper-fidelity gap; revisit if literal Eq. 15 fidelity is
needed.
"""

import numpy as np

from .base import decode_bits, decode_bits_top1, dimension, generation_schedule
from .result import OptimizationResult

LH = 100.0  # standard HGS lower-hunger constant (Yang et al., 2021), inherited unmodified
L_TRANS = 0.03  # l, inherited unmodified from base HGS
THETA_MIN, THETA_MAX = 0.2, 1.2


def run_mhgs(
    evaluator, n_features, pop_size=20, n_generations=100, seed=0, max_evaluations=None, classifier_encoding="multi_hot"
):
    rng = np.random.default_rng(seed)
    D = dimension(n_features)

    positions = rng.uniform(0.0, 1.0, size=(pop_size, D))
    hunger = np.zeros(pop_size)
    fitness = np.empty(pop_size)
    infos = [None] * pop_size

    def evaluate(pos):
        bits = pos > 0.5
        if classifier_encoding == "top1":
            fmask, cmask = decode_bits_top1(bits, pos, n_features, rng)
        else:
            fmask, cmask = decode_bits(bits, n_features, rng)
        return evaluator.evaluate_masks(fmask, cmask)

    for i in range(pop_size):
        fitness[i], infos[i] = evaluate(positions[i])

    best_idx = int(np.argmin(fitness))
    gbest_pos = positions[best_idx].copy()
    gbest_fit = float(fitness[best_idx])
    gbest_info = infos[best_idx]
    history = [(evaluator.n_evaluations, gbest_fit)]

    for t, t_frac in generation_schedule(n_generations, max_evaluations, evaluator):
        fit_best = float(np.min(fitness))
        fit_worst = float(np.max(fitness))

        for i in range(pop_size):
            if np.isclose(fitness[i], fit_best):
                hunger[i] = 0.0
            else:
                denom = fit_worst - fit_best
                denom = denom if abs(denom) > 1e-12 else 1e-12
                r6 = rng.random()
                th = (fitness[i] - fit_best) / denom * r6 * 2.0  # UB-LB = 1
                r = rng.random()
                hnew = LH * (1 + r) if th < LH else th
                hunger[i] += hnew

        sh = float(np.sum(hunger)) or 1e-12

        omega1 = np.empty(pop_size)
        omega2 = np.empty(pop_size)
        for i in range(pop_size):
            r3, r4, r5 = rng.random(), rng.random(), rng.random()
            omega1[i] = (hunger[i] * pop_size / sh * r4) if r3 < L_TRANS else 1.0
            omega2[i] = (1 - np.exp(-abs(hunger[i] - sh))) * r5 * 2.0

        shrink = 2.0 * (1.0 - t_frac)  # Eq. 9 / Eq. 23

        # modified production operator, Eq. 19 (per-agent, greedy keep)
        for i in range(pop_size):
            if rng.random() < 0.6:
                a = rng.random(D)
                x_rand = rng.uniform(0.0, 1.0, size=D)
                candidate = np.clip((1 - a) * positions[i] + a * x_rand, 0.0, 1.0)
                cand_fit, cand_info = evaluate(candidate)
                if cand_fit < fitness[i]:
                    positions[i], fitness[i], infos[i] = candidate, cand_fit, cand_info

        # modified local escaping operator, Eq. 15-18 with modified delta Eq. 22
        order = np.argsort(fitness)
        n_top = min(4, pop_size)
        best4 = positions[order[:n_top]]
        theta = THETA_MIN + (THETA_MAX - THETA_MIN) * (1 - t_frac**3) ** 2
        phi = abs(theta * np.sin(3 * np.pi / 2 + np.sin(theta * 3 * np.pi / 2)))
        best_pos = positions[order[0]].copy()  # snapshot -- must not alias `positions` (mutated below)
        for i in range(pop_size):
            k1 = 2 * rng.random() * phi - phi
            f1 = 1.0 if rng.random() < 0.5 else 0.0
            v1 = f1 * 2 * rng.random() + (1 - f1)
            v2 = f1 * rng.random() + (1 - f1)
            v3 = f1 * rng.random() + (1 - f1)
            delta = 2 * rng.random() * np.abs(np.mean(best4, axis=0) - positions[i])  # Eq. 22
            s_k = rng.uniform(0.0, 1.0, size=D) if rng.random() < 0.5 else positions[rng.integers(pop_size)]
            k2 = rng.standard_normal()  # paper: "k2 is a random number distributed normally"
            if rng.random() < 0.5:
                candidate = positions[i] + k1 * (v1 * best_pos - v2 * s_k) + k2 * k1 * v3 * delta
            else:
                candidate = best_pos + k1 * (v1 * best_pos - v2 * s_k) + k2 * k1 * v3 * delta
            candidate = np.clip(candidate, 0.0, 1.0)
            cand_fit, cand_info = evaluate(candidate)
            if cand_fit < fitness[i]:
                positions[i], fitness[i], infos[i] = candidate, cand_fit, cand_info

        # modified cooperative communication, Eq. 24 (main position update)
        best_pos = positions[int(np.argmin(fitness))].copy()  # snapshot -- must not alias `positions`
        for i in range(pop_size):
            r = rng.uniform(-shrink, shrink)  # Eq. 8: R = 2*Shrink*rand - Shrink
            spread = r * omega2[i] * np.abs(best_pos - positions[i])
            candidate = omega1[i] * best_pos + spread if shrink > rng.random() else omega1[i] * best_pos - spread
            positions[i] = np.clip(candidate, 0.0, 1.0)
            fitness[i], infos[i] = evaluate(positions[i])

        gen_best = int(np.argmin(fitness))
        if fitness[gen_best] < gbest_fit - 1e-9:
            gbest_fit = float(fitness[gen_best])
            gbest_pos = positions[gen_best].copy()
            gbest_info = infos[gen_best]
        history.append((evaluator.n_evaluations, gbest_fit))

    return OptimizationResult(
        best_position=gbest_pos,
        best_fitness=gbest_fit,
        best_info=gbest_info,
        history=history,
        n_evaluations=evaluator.n_evaluations,
    )
